### ISSUE TITLE
onlyNumber is not working

### ISSUE THREAD

**Issue by masabni** [claudiolcastro/vue-fake-input#10]
In the documentation, its mentioned an attr called onlyNumber that suppose to Only allow number input, but this attribute does not work and not even handled in the component code.

otherwise, this package is great, thanks.

**Comment by skibaalex** [comment]
i looked at the components it has not such porp

**Comment by claudiolcastro** [comment]
Hey! thanks for the comment! I realized that I forgot to update the onlyNumber version to the NPM! I will figure this out. Thanks!

**Comment by claudiolcastro** [comment]
@masabni @skibaalex its took time, but.. I've just updated
