### ISSUE TITLE
Wrong path for `main` and `unpkg` from 'package.json'

### ISSUE THREAD

**Issue by doraeminemon** [claudiolcastro/vue-fake-input#2]
Hi, I'm trying to use this package with yarn install, then import ... from keyword. 
However when I run serve with vue-cli it always resolve to not be able to find. I think that it's because of the main and unpkg pointing to non-existing file in the folder. 

If I had time I will make a PR soon for you to review. Meanwhile, I think it's a quick fix that can easily resolve by yourself ( the repo owner ).

If you do fix this, please reply. Thanks !

**Comment by Nikkopala** [comment]
i have the same issue i paste the output of my terminal

`➜  checkin-online-new git:(72-otpcomponent) ✗ yarn add vue-fake-input --dev

yarn add v1.17.3
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning "babel-jest > babel-preset-jest > @babel/plugin-syntax-object-rest-spread@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > babel-core@7.0.0-bridge.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > babel-jest@24.8.0" has unmet peer dependency "@babel/core@^7.0.0".
warning "babel-jest > babel-preset-jest@24.6.0" has unmet peer dependency "@babel/core@^7.0.0".
warning " > sass-loader@7.1.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
[5/5] 🔨  Building fresh packages...
warning "vue-fake-input" is already in "dependencies". Please remove existing entry first before adding it to "devDependencies".
success Saved 1 new dependency.
info Direct dependencies
└─ vue-fake-input@1.0.3
info All dependencies
└─ vue-fake-input@1.0.3
✨  Done in 5.71s.
➜  checkin-online-new git:(72-otpcomponent) ✗ yarn dev                     
yarn run v1.17.3
$ vue-cli-service serve
 INFO  Starting development server...
 98% after emitting SizeLimitsPlugin                                              

 ERROR  Failed to compile with 1 errors                                                                                                                                                          10:23:07 AM

This dependency was not found:

* vue-fake-input in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/@vue/cli-plugin-babel/node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/modules/auth/components/oneTimePassword.vue?vue&type=script&lang=js&

To install it, you can run: npm install --save vue-fake-input
 

`

**Comment by claudiolcastro** [comment]
@doraeminemon @Nikkopala sorry for the delay. just fixed it by adding dist folder. thanks!
